name: aoc2022
version: 0.1.0

dependencies:
  - base >= 4.9 && < 5
  - matrix
  - mtl

ghc-options:
  - -O2

library:
  source-dirs: lib
  exposed-modules:
    - Utils.IO
    - Utils.Parse
    - Utils.Sort

executables:
  Day01:
    main: Main.hs
    source-dirs: src/day01
    dependencies:
      - aoc2022
  Day08:
    main: Main.hs
    source-dirs: src/day08
    dependencies:
      - aoc2022
